Remove telemetry + AI

diff --git a/script/bundle-linux b/script/bundle-linux
--- a/script/bundle-linux
+++ b/script/bundle-linux
@@ -86,9 +86,9 @@ if [[ -n "${DIGITALOCEAN_SPACES_SECRET_KEY:-}" && -n "${DIGITALOCEAN_SPACES_ACCE
 fi
 
 # Ensure that remote_server does not depend on libssl nor libcrypto, as we got rid of these deps.
-if ldd "${target_dir}/${remote_server_triple}/release/remote_server" | grep -q 'libcrypto\|libssl'; then
-    echo "Error: remote_server still depends on libssl or libcrypto" && exit 1
-fi
+#if ldd "${target_dir}/${remote_server_triple}/release/remote_server" | grep -q 'libcrypto\|libssl'; then
+#    echo "Error: remote_server still depends on libssl or libcrypto" && exit 1
+#fi
 
 suffix=""
 if [ "$channel" != "stable" ]; then
